import { z } from "zod";

// ─────────────────────────────────────────────────────────────────────────────
// Element Manifest — source of truth for every ad.
//
// This schema is intentionally Figma-ready: per-element fields use the exact
// snake_case names that downstream tools (Bannerbear modifications, future
// Figma importer) expect to read. Top-level manifest keys remain camelCase to
// match the rest of the TS codebase.
//
// Direction of truth:
//   Element Manifest  ─►  Bannerbear modifications  ─►  rendered PNG/JPG
//                    ─►  Figma nodes (later)
// We never read back from the rendered image or from Bannerbear's response to
// reconstruct elements. See docs/BANNERBEAR_AND_FIGMA_STRATEGY.md.
// ─────────────────────────────────────────────────────────────────────────────

export const ElementTypeSchema = z.enum([
  "background",
  "image",
  "logo",
  "text",
  "shape",
  "icon",
  "cta-button",
  "legal",
  "other",
]);
export type ElementType = z.infer<typeof ElementTypeSchema>;

export const ElementRoleSchema = z.enum([
  "headline",
  "subheadline",
  "body",
  "cta",
  "logo",
  "background",
  "hero-image",
  "supporting-image",
  "legal-disclaimer",
  "decorative",
  // Product visual element — typically a device mockup with a platform
  // screenshot composited inside it. The element's `composite_refs` block
  // (when present) traces the composite back to its mockup + screenshot.
  "product_visual",
  "other",
]);
export type ElementRole = z.infer<typeof ElementRoleSchema>;

export const ElementSourceSchema = z.enum([
  "cloudinary",
  "midjourney-manual",
  "bannerbear-template",
  "inline-text",
  "external-url",
  "ai-generated",
  "user-upload",
  // Locally-generated composite (mockup + screenshot via Sharp). Preview-only;
  // production renders should resolve `composite_refs` to either a Cloudinary
  // composite or a fresh re-composite from the original assets.
  "local_mockup_composite",
  // Manually-curated Midjourney output uploaded by the human. The associated
  // element carries a `midjourney` provenance block with prompt_id + upload_id.
  "midjourney_manual_upload",
  // Auto-generated by the OpenAI Images API (DALL-E / gpt-image-1) from the
  // concept's prompt pack — same upload record + provenance shape as the
  // Midjourney path so downstream code is identical.
  "openai_image",
  // Phase 3 — element backed by a row in data/generated-assets.generated.json
  // (Asset Generator output: CTA element, generated background, generated
  // mockup composite, FX overlay, trading-UI widget). Provenance lives in the
  // `generated_asset` block below.
  "generated_asset",
]);
export type ElementSource = z.infer<typeof ElementSourceSchema>;

// Optional Midjourney provenance for elements whose `source` is
// "midjourney_manual_upload". Lets a renderer or auditor trace any rendered
// ad back to the prompt + upload that produced its visual.
//
// `provenance` makes the manual-workflow status explicit, so any consumer
// (audit log, future Figma importer, ZIP exporter) can verify the asset is
// human-uploaded rather than mistakenly tagged. `assignment_id` and
// `target_element_role` are filled in when an explicit assignment drove the
// element (vs. the demo's default first-by-intended-use fallback).
export const ElementMidjourneyMappingSchema = z.object({
  prompt_id: z.string().optional(),
  upload_id: z.string().optional(),
  intended_use: z
    .enum(["background", "hero_visual", "decorative", "moodboard", "texture"])
    .optional(),
  context: z.string().optional(),
  approved: z.boolean().optional(),
  assignment_id: z.string().optional(),
  target_element_role: z
    .enum(["background", "hero_visual", "decorative_1", "decorative_2"])
    .optional(),
  provenance: z
    .object({
      generated_by: z.string().optional(), // "midjourney"
      uploaded_by_user: z.boolean().optional(),
      manual_workflow: z.boolean().optional(),
    })
    .optional(),
});
export type ElementMidjourneyMapping = z.infer<typeof ElementMidjourneyMappingSchema>;

// Optional traceability block for elements that came out of the Asset
// Generator (data/generated-assets.generated.json). Lets a reviewer trace
// the rendered banner back to the asset row + the original brand-input or
// upstream-generated source files that fed the asset.
export const ElementGeneratedAssetSchema = z.object({
  id: z.string().min(1),
  type: z.enum([
    "background",
    "cta",
    "mockup",
    "trading_ui",
    "fx_overlay",
  ]),
  generator: z.string().optional(),
  variant: z.string().optional(),
  tags: z.array(z.string()).optional(),
  // Free-form provenance copied from the asset's source_assets array.
  // Loosely typed so a schema bump on the Asset Generator side doesn't break
  // existing manifests.
  source_assets: z
    .array(
      z.object({
        source_type: z.string().optional(),
        id: z.string().optional(),
        path: z.string().optional(),
        public_path: z.string().optional(),
        role: z.string().optional(),
      }),
    )
    .optional(),
});
export type ElementGeneratedAsset = z.infer<typeof ElementGeneratedAssetSchema>;

// Optional traceability block for product-visual elements built from a
// composite. Lets a future renderer (Bannerbear) ignore the flat composite
// and rebuild from the original mockup + screenshot if needed.
export const ElementCompositeRefsSchema = z.object({
  composite_public_path: z.string().optional(),
  composite_id: z.string().optional(),
  original_mockup_asset_path: z.string().optional(),
  original_mockup_filename: z.string().optional(),
  original_screenshot_asset_path: z.string().optional(),
  original_screenshot_filename: z.string().optional(),
  screenshot_context: z.string().optional(),
  screenshot_context_confidence: z.string().optional(),
  mockup_slot_source: z.string().optional(),
});
export type ElementCompositeRefs = z.infer<typeof ElementCompositeRefsSchema>;

export const ComplianceStatusSchema = z.enum([
  "not-applicable",
  "pending",
  "approved",
  "rejected",
]);
export type ComplianceStatus = z.infer<typeof ComplianceStatusSchema>;

// ── Bannerbear mapping ────────────────────────────────────────────────────────
// How this element is wired into a Bannerbear template layer.
export const ElementBannerbearMappingSchema = z.object({
  layer_name: z.string().optional(),
  text_layer_name: z.string().optional(),
  button_layer_name: z.string().optional(),
  modification_type: z
    .enum(["text", "image_url", "color", "background_color", "none"])
    .optional(),
});
export type ElementBannerbearMapping = z.infer<
  typeof ElementBannerbearMappingSchema
>;

// ── Figma mapping (forward-looking; not used in MVP) ──────────────────────────
// These fields exist so a future Figma importer can read the manifest directly
// and produce editable nodes. Keep optional — the renderer ignores them today.
export const FigmaConstraintsSchema = z.object({
  horizontal: z.enum(["MIN", "MAX", "CENTER", "STRETCH", "SCALE"]).optional(),
  vertical: z.enum(["MIN", "MAX", "CENTER", "STRETCH", "SCALE"]).optional(),
});

export const ElementFigmaMappingSchema = z.object({
  node_type: z
    .enum([
      "FRAME",
      "GROUP",
      "TEXT",
      "RECTANGLE",
      "ELLIPSE",
      "VECTOR",
      "INSTANCE",
      "COMPONENT",
    ])
    .optional(),
  component_role: z.string().optional(),
  style_ref: z.string().optional(),
  constraints: FigmaConstraintsSchema.optional(),
  exportable: z.boolean().optional(),
  auto_layout_hint: z.enum(["horizontal", "vertical", "none"]).optional(),
  parent_frame_hint: z.string().optional(),
});
export type ElementFigmaMapping = z.infer<typeof ElementFigmaMappingSchema>;

// ── Box helpers ───────────────────────────────────────────────────────────────
const PaddingSchema = z.object({
  top: z.number().optional(),
  right: z.number().optional(),
  bottom: z.number().optional(),
  left: z.number().optional(),
});

const ShadowSchema = z.object({
  x: z.number().optional(),
  y: z.number().optional(),
  blur: z.number().nonnegative().optional(),
  spread: z.number().optional(),
  color: z.string().optional(),
});

// ── Element ───────────────────────────────────────────────────────────────────
// All fields beyond the core block are optional — a text element will use the
// "Text fields" group, an image element the "Image fields" group, etc.
export const ElementSchema = z.object({
  // Core
  id: z.string().min(1),
  type: ElementTypeSchema,
  role: ElementRoleSchema,
  source: ElementSourceSchema,
  asset_id: z.string().optional(),
  x: z.number(),
  y: z.number(),
  width: z.number().nonnegative(),
  height: z.number().nonnegative(),
  z_index: z.number().int(),
  opacity: z.number().min(0).max(1).default(1),
  rotation: z.number().default(0),
  visible: z.boolean().default(true),
  version: z.number().int().nonnegative().default(1),

  // Text fields
  text: z.string().optional(),
  copy_source: z
    .enum(["marketing-translator", "brand", "system", "user", "unknown"])
    .optional(),
  font_family: z.string().optional(),
  font_weight: z.union([z.number().int(), z.string()]).optional(),
  font_size: z.number().positive().optional(),
  line_height: z.number().positive().optional(),
  letter_spacing: z.number().optional(),
  text_align: z.enum(["left", "center", "right", "justify"]).optional(),
  color: z.string().optional(),
  // Headline emphasis prefix. Must be a prefix of `text` (the renderer
  // doesn't search/match — it slices). `emphasis_style` controls the visual
  // treatment without changing font, size, line-height, or layout boxes.
  emphasis_text: z.string().optional(),
  emphasis_color: z.string().optional(),
  emphasis_style: z
    .enum(["accent_color", "underline", "outline", "solid"])
    .optional(),

  // Image fields
  file_url: z.string().url().optional(),
  cloudinary_public_id: z.string().optional(),
  // The local public path used by the dev-mode preview (e.g. /generated-
  // preview-composites/laptop-stocks.png). Preserved alongside any Cloudinary
  // URL so a manifest read in isolation can still resolve to the local file.
  local_public_path: z.string().optional(),
  // Where the renderer should pull the bytes from. "cloudinary" is preferred
  // when uploads exist; "local_preview" is the dev-mode fallback.
  delivery_source: z.enum(["cloudinary", "local_preview"]).optional(),
  object_fit: z.enum(["cover", "contain", "fill", "none", "scale-down"]).optional(),
  crop: z
    .object({
      x: z.number(),
      y: z.number(),
      width: z.number().nonnegative(),
      height: z.number().nonnegative(),
    })
    .optional(),
  alt_text: z.string().optional(),

  // Shape / button fields
  background_color: z.string().optional(),
  border_color: z.string().optional(),
  border_width: z.number().nonnegative().optional(),
  border_radius: z.number().nonnegative().optional(),
  padding: PaddingSchema.optional(),
  shadow: ShadowSchema.optional(),

  // Compliance
  required: z.boolean().optional(),
  compliance_status: ComplianceStatusSchema.optional(),
  risk_warning: z.string().optional(),
  legal_review_required: z.boolean().optional(),

  // Brand
  brand_token_refs: z.array(z.string()).optional(),
  uses_approved_color: z.boolean().optional(),
  uses_approved_font: z.boolean().optional(),
  source_approved: z.boolean().optional(),

  // External system mappings
  bannerbear: ElementBannerbearMappingSchema.optional(),
  figma: ElementFigmaMappingSchema.optional(),

  // Composite traceability (set on product_visual elements when a local
  // composite was used).
  composite_refs: ElementCompositeRefsSchema.optional(),

  // Midjourney provenance (set on elements built from a Midjourney upload).
  midjourney: ElementMidjourneyMappingSchema.optional(),

  // Generated-asset provenance (Phase 3). Set on elements that adopted a row
  // from data/generated-assets.generated.json — CTA element, generated
  // background, generated mockup composite, FX overlay, trading-UI widget.
  generated_asset: ElementGeneratedAssetSchema.optional(),

  // Free-form notes (license, attribution, internal annotation)
  license: z.string().optional(),
  notes: z.string().optional(),
});
export type Element = z.infer<typeof ElementSchema>;

// ── Manifest ──────────────────────────────────────────────────────────────────
export const ElementManifestSchema = z.object({
  manifestId: z.string().min(1),
  specId: z.string().min(1),
  conceptId: z.string().min(1),
  campaignId: z.string().min(1),
  bannerbearTemplateUid: z.string().min(1),
  size: z.object({
    width: z.number().int().positive(),
    height: z.number().int().positive(),
  }),
  elements: z.array(ElementSchema).min(1),
  generatedAt: z.string(),
  schemaVersion: z.string().default("1.0.0"),
});
export type ElementManifest = z.infer<typeof ElementManifestSchema>;
