#!/usr/bin/env tsx
/**
 * Rebuild the Element Manifests of an existing CampaignPlan using the
 * CURRENT layout code, without calling the AI again.
 *
 * The saved campaign-plan.json contains:
 *   - source_brief                        (the user input)
 *   - concept stubs (name, copy, design_elements, midjourney_prompt_pack)
 *   - concept.visual_layout_spec          (the AI's design plan)
 *   - concept.ad_specs[].manifest         (the rendered manifest — what
 *                                          becomes pixels in the PNG)
 *
 * The MANIFEST is a snapshot of the layout-code output at generation time.
 * When you change the renderer (clamps, fitFontToBox, applyComposition…),
 * old saved campaigns DON'T pick up the fixes — their manifest is frozen.
 *
 * This script feeds the saved spec back through `buildConceptsFromPlan`
 * with the current code and overwrites the manifest. After running it
 * call `/api/render-campaign` (or `npm run render:code-campaign`) to
 * capture the new PNGs.
 *
 * Usage:
 *   npm run campaign:rebuild -- --campaign-id=cam_xxxxxxxx
 *   npm run campaign:rebuild -- --all     (rebuilds every campaign)
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import {
  CampaignPlanSchema,
  type CampaignPlan,
} from "@/lib/schemas/aiCampaignPlan.schema";
import {
  loadAdBuildContext,
  buildConceptsFromPlan,
} from "@/lib/ai/buildAdSpecsFromPlan";
import { CampaignBriefSchema } from "@/lib/schemas/campaignBrief.schema";

function parseFlag(name: string): string | undefined {
  const arg = process.argv.find((a) => a.startsWith(`${name}=`));
  return arg?.split("=").slice(1).join("=");
}

async function rebuildOne(campaignId: string, cwd: string): Promise<void> {
  const planPath = path.join(cwd, "data", "campaigns", campaignId, "campaign-plan.json");
  const original = CampaignPlanSchema.parse(
    JSON.parse(await fs.readFile(planPath, "utf8")),
  );
  const ctx = await loadAdBuildContext({ cwd });
  const visualSpecsByConceptId = new Map(
    original.concepts.flatMap((c) =>
      c.visual_layout_spec ? [[c.concept_id, c.visual_layout_spec] as const] : [],
    ),
  );
  const raw = {
    campaign_name: original.campaign_name,
    campaign_summary: original.campaign_summary,
    concepts: original.concepts.map((c) => ({
      concept_id: c.concept_id,
      name: c.name,
      strategic_idea: c.strategic_idea,
      target_emotion: c.target_emotion,
      tone: c.tone,
      visual_direction: c.visual_direction,
      copy_package: c.copy_package,
      desired_visual_context: c.desired_visual_context,
      midjourney_prompt_pack: c.midjourney_prompt_pack,
      design_elements: c.design_elements,
    })),
  };
  const brief = CampaignBriefSchema.parse(original.source_brief);
  const { concepts, warnings } = buildConceptsFromPlan({
    context: ctx,
    brief,
    campaign_id: original.campaign_id,
    raw,
    visualSpecsByConceptId,
  });
  // Drop old per-build warnings (they're regenerated by the new build); keep
  // anything else the user might care about. We strip:
  //   · `downgrade:`                    — re-emitted by the rebuild
  //   · "Using brand-input/Elements/…"  — design-by-default, no longer emitted
  //   · "Using Midjourney upload as …"  — design-by-default, no longer emitted
  // The dedupe at the end collapses any line that still repeats.
  const STALE_PREFIXES = [
    "downgrade:",
    "Using brand-input/Elements/",
    "Using Midjourney upload as background",
  ];
  const isStale = (w: string): boolean =>
    STALE_PREFIXES.some((p) => w.startsWith(p));
  const seen = new Set<string>();
  const merged: string[] = [];
  for (const w of [
    ...original.warnings.filter((w) => !isStale(w)),
    ...warnings,
  ]) {
    if (!seen.has(w)) {
      seen.add(w);
      merged.push(w);
    }
  }
  const next: CampaignPlan = CampaignPlanSchema.parse({
    ...original,
    concepts,
    warnings: merged,
  });
  await fs.writeFile(planPath, JSON.stringify(next, null, 2) + "\n", "utf8");
  const ads = concepts.reduce((a, c) => a + c.ad_specs.length, 0);
  console.log(`  ${campaignId} — ${concepts.length} concepts, ${ads} ads`);
}

async function main() {
  const cwd = process.cwd();
  const all = process.argv.includes("--all");
  const id = parseFlag("--campaign-id");
  const campaignsDir = path.join(cwd, "data", "campaigns");

  let ids: string[];
  if (all) {
    const entries = await fs.readdir(campaignsDir);
    ids = entries.filter((e) => e.startsWith("cam_"));
    console.log(`Rebuilding ${ids.length} campaign manifests…`);
  } else if (id) {
    ids = [id];
  } else {
    console.error(
      "Usage: npm run campaign:rebuild -- --campaign-id=cam_xxxxxxxx | --all",
    );
    process.exit(1);
  }

  let ok = 0;
  let fail = 0;
  for (const cid of ids) {
    try {
      await rebuildOne(cid, cwd);
      ok += 1;
    } catch (err) {
      fail += 1;
      console.error(`  ${cid} — FAILED: ${(err as Error).message.slice(0, 100)}`);
    }
  }
  console.log("");
  console.log(
    `Done. ${ok} rebuilt${fail > 0 ? `, ${fail} failed` : ""}. Run \`npm run render:code-campaign\` (per-campaign) or call /api/render-campaign to refresh the PNGs.`,
  );
}

main().catch((err) => {
  console.error("rebuild failed:", (err as Error).message);
  process.exit(1);
});
